migration4

diff --git a/.github/workflows/sync-provider.yml b/.github/workflows/sync-provider.yml
--- a/.github/workflows/sync-provider.yml
+++ b/.github/workflows/sync-provider.yml
@@ -44,6 +44,17 @@ jobs:
             echo "$SYNCIGNORE not found! Stopping sync..."
             exit 1
           fi
+      
+      - name: Ensure rsync is installed
+        run: |
+          if ! command -v rsync >/dev/null 2>&1; then
+            echo "rsync not found, installing..."
+            sudo apt-get update
+            sudo apt-get install -y rsync
+          else
+            echo "rsync already installed"
+            rsync --version
+          fi
 
       - name: Generate unique temporary directory
         id: temp_dir
@@ -56,8 +67,6 @@ jobs:
 
       - name: Sync REPO_A to TARGET_REPO
         run: |
-          sudo apt-get update
-          sudo apt-get install -y rsync
           rsync -av --exclude-from="$SYNCIGNORE" "$GITHUB_WORKSPACE/" "$TEMP_DIR/target_repo/"
       - name: Configure Git user
         run: |
